# Generated by Django 6.0.2 on 2026-02-26 01:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surgery_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('requires_file', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'preparation_templates',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('district_doctor', 'Участковый врач'), ('surgeon', 'Хирург'), ('patient', 'Пациент'), ('admin', 'Администратор')], default='patient', max_length=30)),
                ('medical_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True)),
                ('passport_series', models.CharField(blank=True, max_length=10, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_issued_by', models.TextField(blank=True, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('snils', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_policy', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis_icd10', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis_text', models.TextField(blank=True, null=True)),
                ('surgery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('red', 'Красный'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('blue', 'Синий')], default='red', max_length=20)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('fhir_data', models.JSONField(blank=True, null=True, verbose_name='FHIR данные')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='IOLCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eye', models.CharField(choices=[('right', 'Правый'), ('left', 'Левый')], max_length=10)),
                ('k1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('k2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('axial_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('formula_used', models.CharField(choices=[('srk_t', 'SRK/T'), ('holladay', 'Holladay'), ('hoffer_q', 'Hoffer Q'), ('haigis', 'Haigis'), ('barrett', 'Barrett')], max_length=50)),
                ('result_diopters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
            options={
                'db_table': 'iol_calculations',
            },
        ),
        migrations.CreateModel(
            name='PatientPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.preparationtemplate')),
            ],
            options={
                'db_table': 'patient_preparation',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='patient_files/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patientpreparation')),
            ],
            options={
                'db_table': 'media_files',
            },
        ),
        migrations.CreateModel(
            name='SurgeonFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('status_after', models.CharField(blank=True, choices=[('success', 'Успешно'), ('complications', 'С осложнениями'), ('postponed', 'Отложено'), ('cancelled', 'Отменено')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surgeon_feedback',
            },
        ),
    ]
