# Generated by Django 6.0.2 on 2026-02-26 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='patient_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='app.patient'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='app.patientpreparation'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
