# Generated by Django 6.0.2 on 2026-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mediafile_options_mediafile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
