# Generated by Django 6.0.2 on 2026-02-27 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_surgerfeedback_reexamine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeonfeedback',
            name='comment',
            field=models.TextField(verbose_name='Комментарий для районного врача'),
        ),
        migrations.AlterField(
            model_name='surgeonfeedback',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_referrals', to='app.patient'),
        ),
        migrations.AlterField(
            model_name='surgeonfeedback',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
